### ISSUE TITLE
Customized panel_file is not read correctly with read_steinbock()

### ISSUE THREAD

**Issue by Daria150393** [BodenmillerGroup/imcRtools#79] opened 2022-07-26 12:28 UTC
Hi @nilseling,

I am using a customized image stack and panel ([NB_Panel.csv](https://github.com/BodenmillerGroup/imcRtools/files/9189689/NB_Panel.csv)) for image segmentation with steinbock. When I try to read in steinbock generated data into the SPE, I get:

class: SpatialExperiment 
dim: 47 948370 
metadata(0):
assays(1): counts
rownames(47): Myeloperoxidase MPO CD44 ... GD2-IF CD56-IF
rowData names(0):
colnames: NULL
colData names(6): sample_id ObjectNumber ... minor_axis_length eccentricity
reducedDimNames(0):
mainExpName: NULL
altExpNames(0):
spatialCoords names(2) : Pos_X Pos_Y
imgData names(1): sample_id

The content of rowData is set to NA 

![Bildschirmfoto 2022-07-26 um 14 25 25](https://user-images.githubusercontent.com/44135481/181005276-d135992d-eeb0-4f8e-94f9-a004ee6c05b6.png) 

and colnames is set to NULL. 

It is not a huge problem, because I can set the colnames and rowData manually, just would like to understand where the problem is. 

Thank you!

**Comment by nilseling** [comment] 2022-07-28 10:28
This issue was caused by incorrectly setting `extract_names_from = "channel"`. Therefore, only `DAPI` correctly matched between `rownames(spe)` and `panel[,"channel"]`. Closing now

**Closed by nilseling** 2022-07-28 10:28 UTC
